"""Use one unchanged logo source in both the website and Remotion film."""
import hashlib
import json
from pathlib import Path
import shutil
import struct

ROOT = Path(__file__).resolve().parents[1]


def prepare_brand():
    source_dir = ROOT / 'design/brand'
    brand = json.loads((source_dir / 'brand.json').read_text())
    assert brand['schema'] == 'voirdire-brand/1'
    assert Path(brand['asset']).name == brand['asset']
    source = source_dir / brand['asset']
    data = source.read_bytes()
    assert data[:8] == b'\x89PNG\r\n\x1a\n', 'Logo must be a PNG'
    assert struct.unpack('>II', data[16:24]) == (brand['width'], brand['height']), 'Logo dimensions differ'
    assert hashlib.sha256(data).hexdigest() == brand['sha256'], 'Logo source hash differs'
    view = brand['lockup_view']
    assert 0 <= view['x'] < view['x'] + view['width'] <= brand['width']
    assert 0 <= view['y'] < view['y'] + view['height'] <= brand['height']
    destinations = [ROOT / 'public/brand']
    # Film sources are intentionally omitted from the Vercel upload.
    film_present = (ROOT / 'film/src').is_dir()
    if film_present:
        destinations.append(ROOT / 'film/public/brand')
    for destination in destinations:
        destination.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination / brand['asset'])
    if film_present:
        (ROOT / 'film/src/brand.json').write_text(json.dumps(brand, indent=2) + '\n')
    # Viewport styling removes presentation margins without changing the PNG.
    # Luminance masking keeps the dark matte from hiding the site's grain.
    css = f'''/* Generated by scripts/prepare_brand.py from design/brand/brand.json. */
.brand-lockup{{display:block;position:relative;flex-shrink:0;width:var(--brand-width,180px);aspect-ratio:{view['width']}/{view['height']};overflow:hidden}}
.brand-lockup>img{{display:block;position:absolute;max-width:none;width:{brand['width']/view['width']*100:.8f}%;height:auto;left:{-view['x']/view['width']*100:.8f}%;top:{-view['y']/view['height']*100:.8f}%;mask-image:url('/brand/{brand['asset']}');mask-mode:luminance;mask-size:100% 100%;mask-repeat:no-repeat}}
'''
    (ROOT / 'public/brand/brand.css').write_text(css)


if __name__ == '__main__':
    prepare_brand()
